### ISSUE TITLE
llff_trained_model.zip missing

### ISSUE THREAD

**Issue by bela333** [Philippus229/LLFF-Toolbox#1]
Hello!

It seems like the original link to llff_trained_model.zip has been taken down. Do you by any chance have a copy laying around somewhere?

Thanks!

**Comment by Philippus229** [comment]
I uploaded it to Dropbox and updated the Jupyter Notebook accordingly. It should work now, but I'd recommend trying to run the COLMAP feature mapping on your PC first (especially if you've got a decent GPU) since that can take around 1 hour in Colab. When I ran it on my PC, however, everything just froze after some time and I had to turn it off by holding down the power button.

**Comment by bela333** [comment]
Thank you!
